biolab/orange-translations

orange3/si.yaml

Prevod gradnika Distances v slovenščino.
Problemi:
- pairwise matrix: "parna matrika razdalj"?
- uporaba trpnika v sporočilih: da/ne?
- https://github.com/biolab/orange3/issues/6166

Translate Distances

---

orange3/si.yaml

Exemplary collection of complicated plural forms! :)

Datainfo: Slovenian translation

---

orange3/si.yaml

Missing translations in various widgets + translation of Neighbor and Correlation, which are in data directory but in a different category

Data category: Some missing translations

---

orange3/si.yaml

Mučen prevod gradnika Box Plot.
Pomisleki:
- je "škatla z brki" v redu prevod?
- celoten razdelek o urejanju spremenljivk (npr. `Order by 𝜒² or ANOVA over the variable values: "Uredi glede na vrednost 𝜒² ali ANOVA za vrednosti spremenljivke"`)
- rezultati testa 𝜒² (se dof prevede ali ne?)
- pretvorba `.format` v f-stringe

Translate Box Plot

---

orange3/si.yaml

Prevod gradnika Nomogram v slovenščino.
Problemi:
- ranking == uvrščanje, razvrščanje, vrednotenje??
- target class == tarčni razred?
- naive Bayes == naivni Bayesov klasifikator?
- log odds == logaritem verjetnosti?

Translate Nomogram

---

si/orange3.yaml

Data: Zalini popravki slovenskih prevodov

---

si/orange-canvas.yaml
si/trubar-config.yaml

Na nekaterih mestih bo tole padlo zaradi https://github.com/janezd/trubar/issues/45. Najbrž je vseeno primerno za pregled.

Canvas: Slovenian translation

---

si/orange3.yaml

Orange dodaja nekaj opcij, ki jih je bilo potrebno prevesti.
Zraven sem pritihotapil par drobnarij v Paint.

Slovenian translation for part of canvas in Orange3

---

si/orange3.jaml

Most of remaining missing translations, and some other fixes.

Orange3: General mop-up

---

si/orange3.jaml

Missing translations for distances in slovenian translation.

Distances: Missing translation (si)

---

si/orange3-geo.jaml

Nekaj posodobitev prevodov glede na spremembe v widgetih ipd.

Geo: Update of Slovenian translation

---

si/orange3-imageanalytics.jaml

Add-on Image Analytics translated (si).

Image analytics: Translation (si)

---

si/orange3.jaml

Wrong translations for model kNN.

kNN: fixed wrong translation (si)

---

si/orange3-imageanalytics.jaml

Better translation in import images.

Import images: fixed translation

---

si/orange-canvas-core.yaml

Canvas Core: Two minor fixes in Slovenian translation

---

si/orange-canvas-core.yaml
si/orange-widget-base.yaml
si/orange3-geo.jaml
si/orange3.jaml

Fixed Slovenian translations in general.

Fixed translations in general (si)

---

si/orange-widget-base.yaml

Updated non-translated strings (after trubar collect) in widget base (si).

Widget base translation updated (si)

---

si/orange3-imageanalytics.jaml

Updated non-translated strings (after trubar collect) in image analytics (si).

Image analytics translation updated (si)

---

si/orange3-geo.jaml

Geo Add-on: updated keywords for every widget and some small updated non-translated lines. (si)

Geo: all widgets translation update (si)

---

si/orange3.jaml

There was update on how keywords for every widget were written. Now translation si updated. (si)

All widgets: keywords updated (si)

---

si/orange3.jaml

Updated non-translated manifold learning (si).

Manifold learning: translation (si)

---

si/orange3.jaml

Updated non-translated lines in evaluate widgets (all widgets that are in evaluate folder).

Evaluate widgets: updated translation (si)

---

si/orange3.jaml

Updated non-translated lines in model widgets (all widgets that are in model folder).

Model widgets: updated translation (si)

---

si/orange3.jaml

Updated non-translated lines in unsupervised widgets (all widgets that are in unsupervised folder).

Unsupervised widgets: updated translation (si)

---

si/orange3.jaml

Updated non-translated lines in visualize widgets (all widgets that are in visualize folder).

Visualize widgets: updated translation (si)

---

si/orange3.jaml

Updated translation for learning rate (si).

Manifold learning: learning rate translation (si)

---

si/orange3.jaml

Updated non-translated outliers (si).

Outliers: translation (si)

---

si/orange3.jaml

Updated non-translated SGD (si).

SGD: translation (si)

---

si/orange3.jaml

Updated Continuize translation because widget was changed/modified in source code.

Continuize: translation update (si)

---

si/orange3.jaml

Updated non-translated lines in data sets and data sampler files.

Data sets, Data sampler: translation update (si)

---

si/orange3.jaml

All other non-translated lines in file are now translated.

Random non-translated lines (si)

---

si/orange3.jaml

Updated non-translated lines in files that are in any way connected to Table (Data Table, sql table).

Table: translation update (si)

---

si/orange3.jaml

Update translation for Continuize widget (preset, ordinal).

Continuize: preset, ordinal translation (si)

---

si/orange3.jaml

With new orange3 pull and then collect, came some changes in translation (si).

Merge Data: translation update (si)

---

si/orange3-geo.jaml
si/orange3.jaml

Updated `: null` after pull and collect.

orange3 and orange3-geo: Update with new messages

---

si/orange3.jaml

orange3: Update with new messages

---

si/orange-widget-base.yaml

Updated all `: null` after pull and collect on orange widget base.

orange widget base: update (si)

---

si/orange-canvas-core.yaml
si/orange3-imageanalytics.jaml
si/orange3.jaml

Updated all `: null` after pull and collect on orange3, cavas core and image analytics (and some minor translate change).

orange3, canvas core, image analytics: update (si)

---

si/orange3.jaml

Updated all `: null` after pull and collect on orange3.

Orange3: update (si)

---

si/orange-canvas-core.yaml
si/orange3.jaml

Updated all `: null` after pull and collect on Orange3 and Orange canvas core.

Orange3, Orange canvas core: update (si)

---

si/orange3-imageanalytics.jaml

Updated all `: null` after pull and collect on Orange3 Image analytics.

Orange3 Image analytics: update (si)

---

si/orange3-text.jaml
si/orange3.jaml

Updated all `: null` after pull and collect on Orange3 and Text add-on.

Orange3, Orange3-Text: Update (si)

---

si/orange-canvas-core.yaml

Updated all `: null` after pull and collect on Orange canvas core.

Updated translation in Orange canvas (si)

---

si/orange-widget-base.yaml
si/orange3-text.jaml
si/orange3.jaml

Updated all `: null` after pull and collect on Orange3, Orange3 Text, Orange canvas core and Orange widget base.

Orange3, Orange3 Text, Orange widget base, canvas core: update (si)

---

si/orange3-imageanalytics.jaml
si/orange3.jaml

Updated all `: null` after pull and collect on Orange3 and Orange3 Image analytics.

Orange3, Orange3 Image analytics: update (si)
